replicaCount: 1
image:
  repository: ocrcontreg/ocr-html-parser
  pullPolicy: Always
  tag: latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 8000
secret:
  name: ocr
configmap:
  name: ocr-configmap
env: dev
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
