header_data = {
    "documentDate": "PODate",
    "deliveryDate": "DlvDate",
    "paymentTerms": "PayTerm",
    # "netAmount": "NetAmount",
    "poNumber": "CustPo",
    "billToName": "BillName",
    "billToStreet": "BillStreet",
    "billToCity": "BillCity",
    "billToPostalCode": "BillZip",
    "shipToCity": "ShipCity",
    "shipToStreet": "ShipStreet",
    "shipToPostalCode": "ShipZip",
    "shipToName": "ShipName",
    # "CMIR": "CMIR",
    "IncoTerm":"IncoTerm",
    "IncoTerm2":"IncoTerm2",
    "shipToAddress": "ShipAddress",
    "shippingInstructions": "Shipinst",
    "billToAddress": "BillAddress",
    "shipTo": "ShipTo",
    "billTo": "BillTo",
    "CustPoCc": "CustPoCc",
#    "SalesOrgCc": "SalesOrgCc",
    "quantityCc": "QuantityCC",
    "SalesOrgName": "SalesName",
    "SalesOrgStreet": "SalesStreet",
    "SalesOrgCity": "SalesCity",
    "SalesOrgZip": "SalesZip",
    "documentNumber": "CustPo",
    "PODate": "PODate",
    "soldToCountry": "CountryTemplate",
    "ocrRegion": "Region",
    "soldToName": "SoldToName"
      }

line_item_data = {
    "currencyCode": "Currency",
    "description": "MatDesc",
    "materialNumber": "Material",
    "customerMaterialNumber": "Material",
    "quantity": "Quantity",
    "unitPrice": "UnitPrice",
    "AsopNo":"AsopNo",
    "OCRItemno": "OCRItemno",
    "materialNumberCc": "MaterialCC",
    "billToCc": "SoldToCc",
    "shipToCc": "ShipToCc",
    "quantityCc": "QuantityCC",
    "itemdeliverydate": "DlvDate",
    "documentDate": "DlvDate",
    "unitOfMeasure": "Uom",
    "ManufactCode": "Material",
    "OCRitemNumber": "POItemNo"
}      

metadata = {"poNumber": "CustPoCc",
#            "SalesOrg": "SalesOrgCc",
            "materialNumber": "materialNumberCc",
            "billTo": "billToCc",
            "shipTo": "shipToCc",
            "quantity": "quantityCc",
            "documentNumber": "CustPoCc",
            "customerMaterialNumber": "materialNumberCC"}
