apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "archival.fullname" . }}
  labels:
    {{- include "archival.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "archival.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: archival
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: {{ .Values.configmap.name }}
                - secretRef:
                    name: {{ .Values.secret.name }}  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
