apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "archival.fullname" . }}
  labels:
    {{- include "archival.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "archival.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "archival.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "archival.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}                
          command: ["sleep", "infinity"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
