replicaCount: 1
image:
  repository: vishalsunilpatil/ocr-csv-parser
  pullPolicy: Always
  tag: s4-dev-0606
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 8000
secret:
  name: ocr
configmap:
  name: ocr-configmap
env: dev
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
