MIN_FILE_SIZE_BYTES = 5
PROCESSING_STATUS = 'PROCESSING'
PDF_CONTENT = 'application/pdf'
XLSX_CONTENT = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
XLSM_CONTENT = 'application/vnd.ms-excel.sheet.macroenabled.12'
SPREADSHEET_CONTENT = [XLSM_CONTENT, XLSX_CONTENT]
CSV_CONTENT = ['text/csv', 'application/csv', 'application/vnd.ms-excel']
HTML_CONTENT = ['text/html', 'application/html', 'application/xhtml+xml']
SUPPORTED_FILE_TYPES = [PDF_CONTENT, *SPREADSHEET_CONTENT, *CSV_CONTENT, *HTML_CONTENT]
SUPPORTED_REGIONS = ['US', 'EMEA', 'LATAM']