replicaCount: 1
image:
  repository: vismay29/dev-archival
  pullPolicy: Always
  tag: "latest"

  

schedule: "0 0 * * *"
concurrencyPolicy: Forbid
archival:
  period_days: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env: 'dev'
ARCHIVAL_PERIOD_DAYS: "3"

secret:
  name: ocr

configmap:
  name: ocr-archival-configmap

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
