# File handling data mappings, anchor fields and other auxiliary items required for data processing and tranformation
data_dimensions={
    "PODate": "date_type",
    "DlvDate": "date_type",
    "CustPo": "possible_singular",
    "BillTo": "listed",
    "ShipTo": "listed",
    "contactname": "multi",
    "CustPhone": "singular",
    "email": "singular",
    "faxordersto:": "singular",
    "e-mailordersto:": "singular",
    "name:": "multi",
    "city": "multi",
    "SoldTo": "singular",
    "Payer": "singular",
    "IncoTerm": "singular",
    "IncoTerm2": "singular",
    "melplant#": "singular",
    "ordertype": "singular",
    "SalesOrg": "singular",
    "itemcategory": "singular",
    "shippingcondition": "singular",
    "deliverylocation:": "singular",
    "podate:": "singular",
    "state/region": "multi",
    "streetnamenumber": "multi",
    "postalcode": "multi",
    "CostCentre": "singular",
    "InternalOrder": "singular",
    "Shipinst": "possible_singular",
    "ShipStreet": "possible_singular",
    "ShipAddress": "possible_singular",
    "SalesDocType": "singular",
    "SoldToName": "singular",
    "ShippingCond": "singular",
    "ItemCat": "singular"
}

data_mapping = {
    "REQUESTEDDELIVERYDATE": "DlvDate",
    "PO#(required)": "CustPo",
    "BILLTO": "BillTo",
    "SHIPTO": "ShipTo",
    "PRODUCTDESCRIPTION": "MatDesc",
    "OrderCode": "Material",
    "#ofCases": "Quantity",
    "Qty": "Quantity",
    "Product": "Material",
    "NumberofCases": "Quantity",
    "Name:": "Name",
    "City": "City",
    "MELSold-To": "SoldTo",
    "MELShip-To": "ShipTo",
    "MELBill-To": "BillTo",
    "IncoTerm:": "IncoTerm",
    "IncoTerm2:": "IncoTerm2",
    "SalesOrg:": "SalesOrg",
    "MELSKU#": "Material",
    "KitDescription": "MatDesc",
    "Quantity(UNITS)": "Quantity",
    "CustomerPONumber": "CustPo",
    "CustomerPO#": "CustPo",
    "StreetNameNumber": "Street",
    "PostalCode": "Zip",
    "ORDERDATE": "PODate",
    "PODate:": "PODate",
    "CS.": "CasesQuantity",
    "EA.": "EachesQuantity",
    "MATERIAL": "Material",
    "DESCRIPTION": "MatDesc",
    "*REQUESTEDDELIVERYDATE(DeliveredbyMEC)": "DlvDate",
    "*SHIPTO/PICKUPADDRESS": "ShipStreet",
    "ITEM#": "Material",
    "ITEMDESCRIPTION": "MatDesc",
    "MATERIAL#": "Material",
    "SALESORG": "SalesOrg",
    "CASES": "Quantity",
    "OrderDate:": "PODate",
    "(FullTimeRemoteEmployeesOnly)ShippingAddress:": "ShipTo",
    "(NottobeusedforCorporateorRialtoWarehouseemployees)ShippingAddress:": "ShipTo",
    "DELIVERYDATE": "DlvDate",
    "ORDERSUBMITDATE": "PODate",
    "SHIPTO/PICKUP-CONTACT&ADDRESS": "ShipAddress",
    "*COSTCENTER/INTERNALORDER#": "CostCentre",
    "COSTCENTER": "CostCentre",
    "INTERNALORDER#": "InternalOrder",
    "SPECIALDELIVERYINSTRUCTIONS": "Shipinst",
    "Phone:": "CustPhone",
    "RequestedDeliveryDate": "DlvDate",
    "SalesOrganisation": "SalesOrg",
    "SoldtoNumber": "SoldTo",
    "CCEPPONumber": "CustPo",
    "ProductDescription": "MatDesc",
    "MonsterSKU": "Material",
    "CasesOrdered": "Quantity",
    "Shipto": "ShipTo",
    "DeliveryDate": "DlvDate",
    "ORDERSUBMITDATE*": "PODate",
    "ORDERTYPE*": "SalesDocType",
    "SOLDTOCUSTOMER": "SoldToName",
    "SHIPTOADDRESS*": "ShipTo",
    "SOLDTO#": "SoldTo",
    "CUSTOMER#": "SoldTo",
    "PACKAGE": "MatDesc",
    "DELIVERYDATE*": "DlvDate",
    "SoldtoName": "SoldToName",
    "ShippingCondition": "ShippingCond",
    "ItemCategory": "ItemCat",
    "REQDELDATE": "DlvDate",
    "RequestedDeliveryDateDD/MM/YYYY": "DlvDate",
    "RequestedDeliveryDateDD-MM-YYYY": "DlvDate",
    "ORDERTYPE": "SalesDocType",
    'CustomerPO': 'CustPo',
    'CustomerPODate': 'PODate',
    'MaterialNumber': 'Material',
    'Qty': 'Quantity',
    'ITEMNUMBER': 'Material',
    'QUANTITY': 'Quantity',
    "LoopID": "TemplateInd",
    "Amount/Price": "UnitPrice",
    "MELPayer:": "Payer",

    "OrderType": "SalesDocType",  #US ZEM
    "SalesOrg": "SalesOrg",
    "OrderDate": "PODate"
}

keys = ['DELIVERYCONTACT-EMAIL*',
 'UNIT/SUITE/APT/BLDG',
 'CASES/PALLET',
 'PACKAGE',
 '*TOTALEACHES/CANS(onlyiforderinglessthanfullcases):',
 'REQUESTEDBY',
 'Product',
 'ORDERSUBMITDATE',
 'PostalCode',
 'ORDERSUBMITDATE*',
 'PACKSIZE',
 'Phone:',
 '*EVENTNAME/SAMPLEREASON',
 'SoldtoNumber',
 'OrderDate:',
 'TypeofProduct',
 'EA.',
 '*PALLETJACKREQUIRED-YESorNO?',
 'CS.',
 'SPECIALDELIVERYINSTRUCTIONS',
 'MELPayer:',
 'REQDELDATE',
 'SOLDTO#',
 'PHONE',
 'MATERIAL#',
 '#ofCases',
 'Name:',
 '*SHIPTO/PICKUPADDRESS',
 'IncoTerm:',
 '*UNIT/SUITE/APT,ETC',
 'DeliveryLocation:',
 'SHIPTO/PICKUP-CONTACT&ADDRESS',
 'KitDescription',
 'Quantity(UNITS)',
 'CustomerPONumber',
 'ITEM#',
 'SALESORG',
 '*LIFTGATEREQUIRED-YESorNO?',
 'StreetNameNumber',
 'MonsterSKU',
 'CUSTOMER#',
 'SoldtoName',
 'REQUESTEDDELIVERYDATE',
 'PO#(required)',
 'MATERIAL',
 'ProductDescription',
 'City',
 'DeliveryDate',
 'CASES',
 'E-MailOrdersTo:',
 'RequestedDeliveryDate',
 'DPSKU#',
 'SOLDTO',
 '*COSTCENTER/INTERNALORDER#',
 'SPECIALDELIVERYINSTRUCTIONS:',
 'SalesOrg:',
 'No.ofLoads',
 'PICKUPDATE*',
 'ItemCategory',
 'EmployeeDept:',
 'ORDERDATE',
 'Qty',
 '*REQUESTEDDELIVERYDATE(DeliveredbyMEC)',
 '*ORDERDATE',
 'Wtw/Pallet',
 '*REQUESTEDPICKUPDATE',
 'PODate:',
 'CasesOrdered',
 'ShippingCondition',
 'ItemCategory',
 'BottlerSKU#',
 'RUSHREQUEST',
 'OrderCode',
 'EmployeeName:',
 'Flavour',
 'REQUESTEDBY*',
 'Shipto',
 'DELIVERDATE',
 '*TOTALCASES:',
 'PRODUCTDESCRIPTION',
 'CSWT',
 'WeekCommencing',
 'DELIVERYDATE*',
 'CONTACTNAME',
 '*RECIPIENTEMAIL',
 'SOLDTOCUSTOMER',
 'Pallets',
 'MELSKU#',
 'Size',
 'Cases/Pallet',
 'BILLTO',
 'ORDERTYPE*',
 'IncoTerm2:',
 '(FullTimeRemoteEmployeesOnly)ShippingAddress:',
 'EACHES',
 'CCEPSKU',
 'MELShip-To',
 'INTERNALORDER#',
 'OrderType',
 'State/Region',
 '(NottobeusedforCorporateorRialtoWarehouseemployees)ShippingAddress:',
 'PICKUPDATE',
 'EMAIL',
 'COSTCENTER',
 'MELBill-To',
 '*REQUESTEDBY',
 'NumberofCases',
 'FaxOrdersTo:',
 'SHIPTO',
 'MELSold-To',
 '*PHONENUMBER',
 'ShiptoLocation',
 'SalesOrganisation',
 'ITEMDESCRIPTION',
 'MELPlant#',
 'DELIVERYDATE',
 'BRAND',
 'CCEPPONumber',
 'OrderWeight',
 'TotalCases',
 'SHIPTOADDRESS*',
 'ORDERTYPE',
 'RequestedDeliveryDateDD/MM/YYYY',
 'RequestedDeliveryDateDD-MM-YYYY',
 'CustomerPO#',
 'Ship-To',
 'Sold-To',
 'DocumentType',
 'CustomerPO',
 'CustomerPODate',
 'Plant',
 'MaterialNumber',
 'Qty',
 'Amount/Price',
 'Department',
 'Email:',
 'Company:',
 'ContactName:',
 'Address:',
 'SalesOrg',
 'ITEMNUMBER',
 'QUANTITY',
 'TOTALPRICE',
 'LoopID',
 'Amount/Price',

 'OrderDate' #ZEM
 ]

multi_valued = {
    "Product": "multi_valued",
    "Cases/Pallet": "multi_valued",
    "Wtw/Pallet": "multi_valued",
    "NumberofCases": "multi_valued",
    "#ofCases": "multi_valued",
    "CS.": "multi_valued",
    "EA.": "multi_valued",
    "Qty": "multi_valued",
    "CASES": "multi_valued",
    "QUANTITY": "multi_valued"
}

tabular_keys = {
    "EMEA": {"Material": [
        "Material",
        "Quantity",
        "Uom",
        "MatDesc",
        "CustPo",
        "DlvDate",
        "ItemShipTo",
        "ItemSoldTo",
        "ItemDocType",
        "ItemSalesOrg",
        "ItemPODate",
        "TemplateInd",
        "UnitPrice"
    ]},
    "Other": {"Material": [
        "Material",
        "Quantity",
        "Uom",
        "MatDesc",
        "EachesQuantity",
        "CasesQuantity"]}
}

directional_biases = {'EA.': 'below',
 '(FullTimeRemoteEmployeesOnly)ShippingAddress:': 'right',
 '*REQUESTEDDELIVERYDATE(DeliveredbyMEC)': 'below',
 '*SHIPTO/PICKUPADDRESS': 'below',
 '(NottobeusedforCorporateorRialtoWarehouseemployees)ShippingAddress:': 'right',
 '*COSTCENTER/INTERNALORDER#': 'below'}

non_columnar_entry_keys = {'MATERIAL': -1, 'MATERIAL#': -3}

regional_map_lvl1 = {'EMEA': {'Shipto': 'ItemShipTo',
  'Sold-To': 'ItemSoldTo',
  'Ship-To': 'ItemShipTo',
  'DocumentType': 'ItemDocType',
  'SalesOrg': 'ItemSalesOrg',
  'CustomerPODate': 'ItemPODate'}}

regional_map_lvl2 = {'EMEA': {'ItemShipTo': 'ShipTo',
  'ItemSoldTo': 'SoldTo',
  'ItemDocType': 'SalesDocType',
  'ItemSalesOrg': 'SalesOrg',
  'ItemPODate': 'PODate'}}