ASOP_NO = "0000000000"
OCR_ITEM_NO_START = 10
REGION = "LATAM"
PODOCTYPE = "HTML"

ITEM_HEADER_MARKERS = ("CANTIDAD", "UNIDAD", "DESCRIPC", "PRECIO", "IMPORTE")
TOTAL_LABELS = {"SUBTOTAL", "IVA", "TOTAL"}